name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      if: runner.os == 'Linux'
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Set up Go
      if: runner.os == 'Windows'
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
        arch: amd64

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
